// Persist numeric benchmark evidence without persisting provider error bodies or credentials.
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const [label, executable, ...args] = process.argv.slice(2);
if (!/^[a-z0-9-]+$/.test(label || '') || !executable) process.exit(2);
const output = path.join(__dirname, label + '.jsonl');
const append = value => {
  const row = JSON.stringify({at: new Date().toISOString(), ...value});
  fs.appendFileSync(output, row + '\n');
  console.log(row);
};
append({event: 'start', label});
const child = spawn(executable, args, {stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true});
let buffer = '';
function line(text) {
  const guard = /^test result: (ok|FAILED)\. (\d+) passed; (\d+) failed; (\d+) ignored/.exec(text);
  if (guard) append({event: 'guard', status: guard[1] === 'ok' ? 'PASS' : 'FAIL', passed: +guard[2], failed: +guard[3], ignored: +guard[4]});
  const result = /^(PASS|FAIL)\s+(\S+)\s+(\d+) rounds\s+(\d+) wire\s+([\d.]+)s/.exec(text);
  if (result) {
    const specs = result[1] === 'PASS' ? [...text.slice(result[0].length).matchAll(/(?:^|\|)\s*([^|\[]+)\[/g)].map(x => x[1].trim()) : [];
    const expected = process.env.CHOYA_EXPECT_SPEC;
    const constraintFailed = result[1] === 'PASS' && expected && !specs.some(x => x.toLowerCase() === expected.toLowerCase());
    const status = constraintFailed ? 'FAIL' : result[1];
    const kind = constraintFailed ? 'request-constraint' : result[1] === 'PASS' ? null
      : /per.day|daily|GenerateRequestsPerDay/i.test(text) ? 'daily-quota'
      : /429|rate.limit/i.test(text) ? 'rate-limit'
      : /plate has \d+ specializations|of 3 specializations/.test(text) ? 'specializations'
      : /validation error/.test(text) ? 'validation'
      : /missing weapons/.test(text) ? 'missing-slots'
      : /HTTP|timeout|timed out|body error/.test(text) ? 'transport'
      : /no plate|prose|No JSON|Parse error/.test(text) ? 'output-format'
      : /API error\s*\d{3}/.test(text) ? 'api-' + /API error\s*(\d{3})/.exec(text)[1]
      : /[Nn]o (response|candidate|text)|empty|MAX_TOKENS|MALFORMED_FUNCTION_CALL/.test(text) ? 'empty-or-malformed-output' : 'unclassified';
    // These three messages are generated by local validation from game names;
    // transport/provider error bodies remain excluded.
    const validation_detail = ['validation', 'specializations', 'missing-slots'].includes(kind)
      ? text.slice(result[0].length).trim() : undefined;
    append({event: 'result', status, model: result[2], rounds: +result[3], wire: +result[4], seconds: +result[5], failure_kind: kind, validation_detail, specs});
  } else {
    const round = /^  round (\d+)\/(\d+) ([\d.]+)s: ([a-z_, ]+)$/.exec(text);
    if (round) append({event: 'round', turn: +round[1], max: +round[2], seconds: +round[3], tools: round[4]});
    const prompt = /^prompt (\d+) chars .*?, (\d+) tools/.exec(text);
    if (prompt) append({event: 'prompt', chars: +prompt[1], tools: +prompt[2]});
    // Only classify errors; raw provider messages may contain sensitive input.
    if (/^error/.test(text)) append({event: 'compile-error'});
  }
}
child.stdout.on('data', chunk => {
  buffer += chunk.toString();
  let index;
  while ((index = buffer.indexOf('\n')) >= 0) {
    line(buffer.slice(0, index).replace(/\r$/, ''));
    buffer = buffer.slice(index + 1);
  }
});
child.stderr.on('data', chunk => { if (/error/.test(chunk.toString())) append({event: 'stderr-error'}); });
child.on('error', () => append({event: 'spawn-error'}));
child.on('close', code => {
  if (buffer) line(buffer.trimEnd());
  append({event: 'exit', code});
  process.exitCode = code ?? 1;
});
